version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rottenpotatoes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "1234:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - rottenpotatoes-network

volumes:
  db_data:

networks:
  rottenpotatoes-network:
    driver: bridge
